console.log()
console.log('Local builds are not encouraged! The prefered way is to build with triggers in Azure Devops.')
console.log('There is no guarantee that the build will work on Azure if it works locally.')
console.log('')
console.log('Some things that are probably different with the remote build:')
console.log('')
console.log('\t-> It is run on Linux docker image.')
console.log('\t-> It has no Yarn cache.')
console.log('\t-> It has MyGet credentials stored that are not yours.')
console.log('\t-> It also runs the unit tests.')
console.log('')
console.log('Be wary of artificats that are created during build as they can have unintended consequences.')
console.log('')
console.log('You have been warned!')
console.log('')
